# Docker compose will create network, create volumes and then attach to the containers

networks:
  default:
    external: true
    name: roboshop
services:
# below is equal to docker run -d --name mongodb --network=roboshop mongodb:1
  mongodb:
    image: mongodb:1
    # networks:
    # - roboshop

  catalogue:
    image: catalogue:1
    # networks:
    # - roboshop
    depends_on:
    - mongodb

  web:
    image: web:1
    # networks:
    #   - roboshop
    ports:
    - "80:80"
    depends_on:
    - catalogue

  redis:

  user:
    image: user:1
    depends_on:
    - redis
    - mongodb

  cart:
    image: cart:1
    depends_on:
    - redis
    - catalogue  
      
